import { Day } from './calendar-day.type';
import { TIMESLOT_MOCK_6, TIMESLOT_MOCK_7 } from './timeslot-mock';

export const daysMock: Day[] = [
  {
    number: 26,
    isToday: true,
    isSelected: false,
    isOtherMonth: true,
    isSelectable: true,
    isPast: false,
    dayMonthYearTitle: '2023-12-26',
    slotsArr: TIMESLOT_MOCK_6,
  },
  {
    number: 27,
    isToday: true,
    isSelected: false,
    isOtherMonth: true,
    isSelectable: true,
    isPast: false,
    dayMonthYearTitle: '2023-12-27',
    slotsArr: TIMESLOT_MOCK_6,
  },
];

export const calendarPopulatedDays: Day[] = [
  {
    number: 27,
    isToday: false,
    isSelected: false,
    isOtherMonth: true,
    isSelectable: true,
    isPast: true,
    dayMonthYearTitle: '2023-11-27',
    slotsArr: [],
  },
  {
    number: 28,
    isToday: false,
    isSelected: false,
    isOtherMonth: true,
    isSelectable: true,
    isPast: true,
    dayMonthYearTitle: '2023-11-28',
    slotsArr: [],
  },
  {
    number: 29,
    isToday: false,
    isSelected: false,
    isOtherMonth: true,
    isSelectable: true,
    isPast: true,
    dayMonthYearTitle: '2023-11-29',
    slotsArr: [],
  },
  {
    number: 30,
    isToday: false,
    isSelected: false,
    isOtherMonth: true,
    isSelectable: true,
    isPast: true,
    dayMonthYearTitle: '2023-11-30',
    slotsArr: [],
  },
  {
    number: 1,
    isToday: false,
    isSelected: false,
    isOtherMonth: false,
    isSelectable: false,
    isPast: true,
    dayMonthYearTitle: '2023-12-01',
    slotsArr: [],
  },
  {
    number: 2,
    isToday: false,
    isSelected: false,
    isOtherMonth: false,
    isSelectable: false,
    isPast: true,
    dayMonthYearTitle: '2023-12-02',
    slotsArr: [],
  },
  {
    number: 3,
    isToday: false,
    isSelected: false,
    isOtherMonth: false,
    isSelectable: false,
    isPast: true,
    dayMonthYearTitle: '2023-12-03',
    slotsArr: [],
  },
  {
    number: 4,
    isToday: false,
    isSelected: false,
    isOtherMonth: false,
    isSelectable: false,
    isPast: true,
    dayMonthYearTitle: '2023-12-04',
    slotsArr: [],
  },
  {
    number: 5,
    isToday: false,
    isSelected: false,
    isOtherMonth: false,
    isSelectable: false,
    isPast: true,
    dayMonthYearTitle: '2023-12-05',
    slotsArr: [],
  },
  {
    number: 6,
    isToday: false,
    isSelected: false,
    isOtherMonth: false,
    isSelectable: true,
    isPast: true,
    dayMonthYearTitle: '2023-12-06',
    slotsArr: [],
  },
  {
    number: 7,
    isToday: false,
    isSelected: false,
    isOtherMonth: false,
    isSelectable: true,
    isPast: true,
    dayMonthYearTitle: '2023-12-07',
    slotsArr: [],
  },
  {
    number: 8,
    isToday: false,
    isSelected: false,
    isOtherMonth: false,
    isSelectable: false,
    isPast: true,
    dayMonthYearTitle: '2023-12-08',
    slotsArr: [],
  },
  {
    number: 9,
    isToday: false,
    isSelected: false,
    isOtherMonth: false,
    isSelectable: false,
    isPast: true,
    dayMonthYearTitle: '2023-12-09',
    slotsArr: [],
  },
  {
    number: 10,
    isToday: false,
    isSelected: false,
    isOtherMonth: false,
    isSelectable: false,
    isPast: true,
    dayMonthYearTitle: '2023-12-10',
    slotsArr: [],
  },
  {
    number: 11,
    isToday: false,
    isSelected: false,
    isOtherMonth: false,
    isSelectable: false,
    isPast: true,
    dayMonthYearTitle: '2023-12-11',
    slotsArr: [],
  },
  {
    number: 12,
    isToday: false,
    isSelected: false,
    isOtherMonth: false,
    isSelectable: false,
    isPast: true,
    dayMonthYearTitle: '2023-12-12',
    slotsArr: [],
  },
  {
    number: 13,
    isToday: true,
    isSelected: false,
    isOtherMonth: false,
    isSelectable: true,
    isPast: false,
    dayMonthYearTitle: '2023-12-13',
    slotsArr: [],
  },
  {
    number: 14,
    isToday: false,
    isSelected: false,
    isOtherMonth: false,
    isSelectable: true,
    isPast: false,
    dayMonthYearTitle: '2023-12-14',
    slotsArr: [],
  },
  {
    number: 15,
    isToday: false,
    isSelected: false,
    isOtherMonth: false,
    isSelectable: false,
    isPast: false,
    dayMonthYearTitle: '2023-12-15',
    slotsArr: [],
  },
  {
    number: 16,
    isToday: false,
    isSelected: false,
    isOtherMonth: false,
    isSelectable: false,
    isPast: false,
    dayMonthYearTitle: '2023-12-16',
    slotsArr: [],
  },
  {
    number: 17,
    isToday: false,
    isSelected: false,
    isOtherMonth: false,
    isSelectable: false,
    isPast: false,
    dayMonthYearTitle: '2023-12-17',
    slotsArr: [],
  },
  {
    number: 18,
    isToday: false,
    isSelected: false,
    isOtherMonth: false,
    isSelectable: false,
    isPast: false,
    dayMonthYearTitle: '2023-12-18',
    slotsArr: [],
  },
  {
    number: 19,
    isToday: false,
    isSelected: false,
    isOtherMonth: false,
    isSelectable: false,
    isPast: false,
    dayMonthYearTitle: '2023-12-19',
    slotsArr: [],
  },
  {
    number: 20,
    isToday: false,
    isSelected: false,
    isOtherMonth: false,
    isSelectable: true,
    isPast: false,
    dayMonthYearTitle: '2023-12-20',
    slotsArr: [],
  },
  {
    number: 21,
    isToday: false,
    isSelected: false,
    isOtherMonth: false,
    isSelectable: true,
    isPast: false,
    dayMonthYearTitle: '2023-12-21',
    slotsArr: [],
  },
  {
    number: 22,
    isToday: false,
    isSelected: false,
    isOtherMonth: false,
    isSelectable: false,
    isPast: false,
    dayMonthYearTitle: '2023-12-22',
    slotsArr: [],
  },
  {
    number: 23,
    isToday: false,
    isSelected: false,
    isOtherMonth: false,
    isSelectable: false,
    isPast: false,
    dayMonthYearTitle: '2023-12-23',
    slotsArr: [],
  },
  {
    number: 24,
    isToday: false,
    isSelected: false,
    isOtherMonth: false,
    isSelectable: false,
    isPast: false,
    dayMonthYearTitle: '2023-12-24',
    slotsArr: [],
  },
  {
    number: 25,
    isToday: false,
    isSelected: false,
    isOtherMonth: false,
    isSelectable: false,
    isPast: false,
    dayMonthYearTitle: '2023-12-25',
    slotsArr: [],
  },
  {
    number: 26,
    isToday: false,
    isSelected: false,
    isOtherMonth: false,
    isSelectable: false,
    isPast: false,
    dayMonthYearTitle: '2023-12-26',
    slotsArr: [],
  },
  {
    number: 27,
    isToday: false,
    isSelected: false,
    isOtherMonth: false,
    isSelectable: true,
    isPast: false,
    dayMonthYearTitle: '2023-12-27',
    slotsArr: [],
  },
  {
    number: 28,
    isToday: false,
    isSelected: false,
    isOtherMonth: false,
    isSelectable: true,
    isPast: false,
    dayMonthYearTitle: '2023-12-28',
    slotsArr: [],
  },
  {
    number: 29,
    isToday: false,
    isSelected: false,
    isOtherMonth: false,
    isSelectable: false,
    isPast: false,
    dayMonthYearTitle: '2023-12-29',
    slotsArr: [],
  },
  {
    number: 30,
    isToday: false,
    isSelected: false,
    isOtherMonth: false,
    isSelectable: false,
    isPast: false,
    dayMonthYearTitle: '2023-12-30',
    slotsArr: [],
  },
  {
    number: 31,
    isToday: false,
    isSelected: false,
    isOtherMonth: false,
    isSelectable: false,
    isPast: false,
    dayMonthYearTitle: '2023-12-31',
    slotsArr: [],
  },
];

export const SELECTED_DAY_MOCK: Day = {
  number: 6,
  isToday: false,
  isSelected: true,
  isOtherMonth: false,
  isSelectable: true,
  isPast: true,
  dayMonthYearTitle: '2023-12-06',
  slotsArr: TIMESLOT_MOCK_7,
};

export const SELECTED_DAYS_MOCK: Day[] = [
  {
    number: 6,
    isToday: false,
    isSelected: true,
    isOtherMonth: false,
    isSelectable: true,
    isPast: true,
    dayMonthYearTitle: '2023-12-06',
    slotsArr: TIMESLOT_MOCK_7,
  },
  {
    number: 27,
    isToday: false,
    isSelected: false,
    isOtherMonth: false,
    isSelectable: true,
    isPast: false,
    dayMonthYearTitle: '2023-12-27',
    slotsArr: TIMESLOT_MOCK_7,
  },
];
